### ISSUE TITLE
Question : Is possible to access the current command line arguments 

### ISSUE THREAD

**Issue by chhex** [EncoreTechnologies/puppet-inventory_utils#11]
Great thanks for this great utils!  

Only a quick question here .... probably not the right place, but where? 

If i run a bolt plan as follows for example : 
`bolt plan run some_plan   --user auser --password apassw --targets testvms someparm=whatever`

is it possible to access both types of parameters , eg --user and also someparm in the inventory via plugin task inventory_utils::erb_template in the template? 

Christoph

**Comment by nmaludy** [comment]
@chhex That would be a better question for the core Bolt team. As far as i understand it, the inventory file doesn't have access to the data passed in on the CLI. If you found out otherwise, would love to know how to do it!

**Comment by lucywyman** [comment]
@chhex what are you trying to achieve? The command-line arguments and inventory get merged, but do not have access to each other. FWIW, and this is so confusing that we actually have a warning for it, the inventory options will override any CLI options.

**Comment by chhex** [comment]
@lucywyman yep, i saw that warning...  

the scenario from my point of view is with application level parameters, not the -- parameters reserved for bolt , but the key value pair parameters , which can be referenced as parameters in plans.  

Maybe not a very typical usage scenario , but we have developers provisioning local test vm's on their local machines with bolt and puppet.  And this vm's are running mostly with dhcp, so they have changing ip adresses:

`bolt plan run some_plan --user auser --password apassw --targets testvm  ipadress=mylocalipadress`

It would be great if the target uri of the inventory.yaml group testvm could be dynamically parametrized, for instance with the inventory-utils or such. 

```
name: local
targets:
  - uri: mylocalipadress
```

Naturally the simplest way would be to
 edit the inventory file.... but since the file is under version control and the file would be different for each developer, this can lead to confusion.   A minor one, agreed.  That actually the way we are going currently.

```
name: local
targets:
  - uri: 192.168.1.20
```

Does that make sense?

Btw i think Bolt is really great!

**Comment by chhex** [comment]
@nmaludy So this is more a requirement for Bolt.  Shall i close the issue?

**Comment by nmaludy** [comment]
@chhex yeah i agree, thanks for submitting, i'll close it for now.
